### ISSUE TITLE
_SLOW_CRC32C_WARNING

### ISSUE THREAD

**Issue by leeyunjai82** [googleapis/python-crc32c#139]
/usr/local/lib/python3.7/dist-packages/google_crc32c/__init__.py:29: RuntimeWarning: As the c extension couldn't be imported, `google-crc32c` is using a pure python implementation that is significantly slower. If possible, please configure a c build environment and compile the extension
  warnings.warn(_SLOW_CRC32C_WARNING, RuntimeWarning)
  
This version is 1.3.0

**Comment by parthea** [comment]
See https://github.com/googleapis/python-crc32c/issues/83#issuecomment-910515271 which includes a Dockerfile to avoid using pure python for users who are on non-manylinux Linux platforms. I'm going to close this issue but please feel free to open a new issue with more information. If you're still having issues after trying https://github.com/googleapis/python-crc32c/issues/83#issuecomment-910515271 please also share the `Dockerfile` to help reproduce the issue.
