### ISSUE TITLE
Migrate Release Tooling

### ISSUE THREAD

**Issue by parthea** [googleapis/python-crc32c#149]
Creating an issue to track migrating the release tooling from [GH Action](https://github.com/googleapis/python-crc32c/blob/main/.github/workflows/python-publish.yml) to Kokoro.

**Comment by pjonsson** [comment]
@parthea Since this is blocking the 1.6.0 release, what remains to be done for this work to be completed?

**Comment by parthea** [comment]
In terms of next steps, I believe https://github.com/googleapis/python-crc32c/pull/51 needs to be reverted. The build scripts need to be updated to build the binaries in Kokoro.  I'm not actively working on it. @andrewsg, do you know if this work been scheduled? If not, can you provide a ballpark ETA?

**Comment by andrewsg** [comment]
2024 Q2 is my ballpark ETA. I wouldn't describe the work as scheduled exactly.

**Comment by pjonsson** [comment]
@andrewsg @parthea I realize this isn't an issue for Google, but the python3 package (https://packages.ubuntu.com/noble/python3) in Ubuntu 24.04 LTS is Python 3.12.

The 1.6 release has been blocked since late November, and I get the impression that the work in this ticket could slip beyond Q2, could you make the 1.6 release (or a 1.5.1 release) before that?

**Comment by Oscmage** [comment]
Given that this impacts the performance of the [bigquery client](https://pypi.org/project/google-cloud-bigquery/) which mentions 3.12 support (among other google libraries I assume) I think it would be nice to get this prioritised. It was quite misleading for us to bump to 3.12 after looking at google libraries saying it supports 3.12 and then realise that it works but with worse performance than if we were to run 3.11. Python 3.12 has been released for almost 7 months now and the only option is to build from source.
