### ISSUE TITLE
Python package conflicts with crc32c

### ISSUE THREAD

**Issue by tswast** [googleapis/python-crc32c#29]
This package conflicts with the [crc32c](https://github.com/ICRAR/crc32c) package, which is used in projects such as [snakemake](https://github.com/snakemake/snakemake). This conflict means that older versions of Google client libraries need to be pinned in order to be able to install such packages. See: https://github.com/bioconda/bioconda-recipes/pull/23799

**Comment by tseaver** [comment]
I guess one could argue that we should namespace the actual package as `google.cr3c2c`.  The [ICRAR package](https://pypi.org/project/crc32c/#history) certainly predates ours on PyPI.

I haven't checked yet whether `google-resumable-media` could just use the ICRAR version somehow, allowing us to retire this package.

**Comment by tseaver** [comment]
@dhermes might have some memory about considering use of the ICRAR version.

**Comment by tseaver** [comment]
The PR I just opened for GRMP pins to the existing version.  If we are going to namespace this package, we would need to make a GRMP release with that new pin, then do the work and make a release here, then update GRMP to use the namespaced version and make a release.
