### ISSUE TITLE
Make sure google/crc32c `git` hash is embedded in Python package

### ISSUE THREAD

**Issue by dhermes** [googleapis/python-crc32c#3]
For example:

```python
>>> import numpy.version
>>> numpy.version.git_revision
'f82c2b62d18b381baefc30f8e8d7788d08a0bd16'
```

Except that refers to a [commit][1] within the `numpy/numpy` project, whereas I'm suggesting we refer to a commit of the `google/crc32c` **sub**project.

[1]: https://github.com/numpy/numpy/commit/f82c2b62d18b381baefc30f8e8d7788d08a0bd16

**Comment by busunkim96** [comment]
@crwilcox The friendly triage bot now has access to this repo. 😁   Is this issue still relevant?

**Comment by parthea** [comment]
Closing as obsolete. The git hash is visible for a given release.


![image](https://github.com/googleapis/python-crc32c/assets/5184014/261d9afe-7430-4438-acc2-41379dad2825)
