### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [googleapis/python-crc32c#39]
Summary
Installing google-crc32c on aarch64 via pip using command "pip3 install google-crc32c" tries to build wheel from source code

Problem description
google-crc32c doesn't have wheel for aarch64 on PyPI repository. So, while installing google-crc32c via pip on aarch64, pip builds wheel for same resulting in it takes more time to install google-crc32c. Making wheel available for aarch64 will benefit aarch64 users by minimizing google-crc32c installation time.

Expected Output
Pip should be able to download google-crc32c wheel from PyPI repository rather than building it from source code.

@google-crc32c-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make google-crc32c wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by busunkim96** [comment]
@crwilcox Could you take a look?

**Comment by crwilcox** [comment]
Thanks for the report @odidev, as best I understand, we would need to add an additional build as standard manylinux doesn't seem to handle aarch64? 
https://github.com/pypa/manylinux

**Comment by odidev** [comment]
Thanks for the quick response @crwilcox we have started working on wheel support for aarch64 also manylinux2014 has started aarch64 support.

**Comment by odidev** [comment]
@crwilcox I have created .travis.yml and added jobs to build aarch64 wheels. Modified build.sh and build_on_centos.sh file as well according to the aarch64 platform. Refer to the changes https://github.com/odidev/python-crc32c/commit/add7f3b17a05740327db9af5a21212360e5662f6. 

Please have a look and share your thoughts. Will you be interested in adding Travis-ci for arm64 wheel support?

**Comment by crwilcox** [comment]
@odidev Can you clarify a few things? I see an edit to the build script for manylinux2010 to manylinux2014_aarch. It would seem to me we likely need to build both the old 2010 way and the 2014_aarch? Or is that 2014 with aarch as well?

Also, if the changes are in build.sh and the docker image, do we need to add a dependency on travis?

**Comment by odidev** [comment]
> It would seem to me we likely need to build both the old 2010 way and the 2014_aarch?

We can modify the build.sh script to add architecture check and it is not required to build on both 2010 and 2014 image, 2014 image can be used on aarch64 and x86_64 architecture.

> Or is that 2014 with aarch as well?

manylinux 2014 image has support for both aarch64 and x86_64, Please refer https://github.com/pypa/manylinux

> if the changes are in build.sh and the docker image, do we need to add a dependency on travis?

We do not need to add a dependency on Travis in order to modify the docker image in build.sh.

@crwilcox Please suggest should I go ahead and raise PR for adding Travis-ci for arm64 wheel support.

**Comment by crwilcox** [comment]
As part of https://github.com/googleapis/python-crc32c/pull/57 I added manylinux2014. However, the ubuntu 20.04 runner on CI is erroring out when trying to target aarch64 wheel builds. I left a todo in the code to pick this up in the future.

**Comment by crwilcox** [comment]
@odidev I merged your PR, thank you for adding this. I did notice an oddity though

The wheel is with suffic `linux_aarch64`, but `manylinux2014_aarch64` as I would expect. It seems from your activity you likely know a bit about this. Could you explain?

```
Collecting cffi>=1.0.0
  Using cached cffi-1.14.4-cp38-cp38-manylinux2014_aarch64.whl (208 kB)
Collecting pycparser
  File was already downloaded /var/code/python-crc32c/dist_wheels/pycparser-2.20-py2.py3-none-any.whl
Saved ./dist_wheels/cffi-1.14.4-cp38-cp38-manylinux2014_aarch64.whl
Building wheels for collected packages: google-crc32c
  Building wheel for google-crc32c (PEP 517): started
  Building wheel for google-crc32c (PEP 517): finished with status 'done'
  Created wheel for google-crc32c: filename=google_crc32c-1.1.1-cp38-cp38-linux_aarch64.whl size=25810 sha256=993cb7771ef56bfd8363c59fcc544ad2da1c4db70a7de2666f13bc22dd5c735c
  ```

**Comment by crwilcox** [comment]
Thanks again for the contribution. I am going to modify the readme to list the aarch64 wheels. Expect these wheels to show up in the next release.
