### ISSUE TITLE
Push to PyPI

### ISSUE THREAD

**Issue by dhermes** [googleapis/python-crc32c#5]
- [x] Populate content for all `TODO` fields (description, long_description) in `setup.py`
- [x] Agree on the package import path and the package name for PyPI
- [x] Determine the documentation story 
- [ ] Resolve #3
- [x] Get https://github.com/google/crc32c/pull/23 merged
- [x] Update all built wheels
- [x] **Nice-to-have**: Determine where this repo should live (it has been moved into the [`googleapis`][1] org)
- [ ] **Nice-to-have**: Resolve #4 
- [x] **Nice-to-have**: Automate building of `manylinux` and OS X wheels on Travis (or other platform that will support OS X and Docker)
- [ ] **Nice-to-have**: Instructions on how to build from source (and probably an error message if the `sdist` is on PyPI). This will allow users who REALLY want to optimize the install to build for their hardware.

[1]: http://github.com/googleapis

---

It is currently on PyPI as [`python-crc32c`][2] though it may be a bit redundant to have `python-` in the name of a package on the Python Package Index.

[2]: https://pypi.org/project/python-crc32c/

**Comment by voegtlel** [comment]
Why is the package gone from pipy? It was there a few days ago and we're already using it. This is really frustrating 👎

**Comment by crwilcox** [comment]
Closing this issue out. A version with wheels for windows, linux, mac has been published.
