### ISSUE TITLE
De-dupe test runs for manylinux

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-crc32c#63]
Currently, test runs are matrixed in the github action, as well as centos build. https://github.com/googleapis/python-crc32c/blob/master/scripts/manylinux/build_on_centos.sh against python 3.6...3.10

One or the other can be simplified so we aren't rebuilding/retesting configurations.

**Comment by tseaver** [comment]
See #70:  including 3.10 in the `$VERSION_WHITELIST` is actually breaking the build at the moment.
