### ISSUE TITLE
Publish wheels for ARM64 based Mac OS?

### ISSUE THREAD

**Issue by oittaa** [googleapis/python-crc32c#66]
It would be nice if ARM based Macs were also supported. Is that on a roadmap?

**Comment by scribu** [comment]
Yeah, right now I'm getting an error when trying to run `pip install google-crc32c` on an Apple M1 Macbook Pro:

```
src/google_crc32c/_crc32c.c:3:10: fatal error: 'crc32c/crc32c.h' file not found
```

**Comment by tseaver** [comment]
PR #106 switched our release machinery to use CIBuildWheel, which enabled building `universal2` wheels.  That PR should land in a release on Monday.

@oittaa, @scribu in the meanwhile, if you'd like to try out the `universal2` wheels, you can download the [artifact tarball](https://github.com/googleapis/python-crc32c/suites/3800123153/artifacts/93831382) from the test of that PR.
